# type: ignore
# pylint: skip-file, disable-all

import os
import sys
from os.path import abspath, dirname
from os.path import join as jj
from os.path import realpath

# os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


from loguru import logger as loguru_logger
from snakemake import shell


PACKAGE_PATH = abspath(jj(dirname(realpath(workflow.snakefile)), ".."))

if PACKAGE_PATH not in sys.path:
    sys.path.insert(0, PACKAGE_PATH)

from pyriksprot import sync_delta_names
from pyriksprot_tagger import expand_target_files, setup_logging

from pyriksprot import configuration

typed_config: configuration.Config = configuration.configure_context(
    context="default", source=(config or {}).get("config_filename")
)

setup_logging()

if sys.platform not in ["win32"]:
    shell.prefix("set -o pipefail; ")


rule all:
    input:
        expand_target_files(
            typed_config.source.folder,
            typed_config.source.extension,
            typed_config.target.folder,
            typed_config.target.extension,
            years=config.get("year_filter", None),
        )


include: jj("rules", "help.smk")
include: jj("rules", "update_repository.smk")
include: jj("rules", "compute_frequency.smk")
include: jj("rules", "tag_protocols.smk")


# include: jj("rules", "extract_speeches.smk")


onstart:
    loguru_logger.info("Workflow started")
    os.makedirs(typed_config.target.folder, exist_ok=True)
    os.makedirs(typed_config.data_folder, exist_ok=True)
    os.makedirs(typed_config.log_folder, exist_ok=True)
    # os.makedirs(typed_config.extract.folder, exist_ok=True)



onsuccess:
    sync_delta_names(typed_config.source.folder, "xml", typed_config.target.folder, "xml", delete=True)
    loguru_logger.info("Workflow ended")


onerror:
    loguru_logger.error("Workflow FAILED")
