from os.path import join as jj

from snakemake import shell
from snakemake.io import expand, glob_wildcards
from snakemake.logging import logger

WORKFLOW_PATH = os.path.dirname(os.path.realpath(workflow.snakefile))
PACKAGE_PATH = os.path.abspath(os.path.join(WORKFLOW_PATH, ".."))

if PACKAGE_PATH not in sys.path:
    sys.path.insert(0, PACKAGE_PATH)

import workflow.model.utility as utility

# options: https://snakemake.readthedocs.io/en/stable/executing/cli.html#all-options
shell.prefix("set -o pipefail; ")


configfile: os.path.join(WORKFLOW_PATH, 'config', 'config.yml')


source_folder = config['parla_clarin']['folder']
target_folder = config['transformed_speeches']['folder']
target_extension = config['transformed_speeches']['extension']


onstart:
    print("Starting Workflow")


rule all:
    input:
        expand(
            f'{target_folder}/{{basename}}.{target_extension}',
            basename=glob_wildcards(f"{source_folder}/{{basename}}.xml").basename,
        ),


include: './rules/help.smk'
include: './rules/setup.smk'
include: './rules/to_speeches.smk'


onsuccess:
    if "verbose" in config and config["verbose"]:
        print("\n--- Preprocessing workflow finished successfully! ------------------------------------\n")


onerror:
    print("Workflow ended with error status!")
