#!/bin/bash

SITE_PACKAGES=$(poetry run python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')

echo $SITE_PACKAGES

ln -s $SITE_PACKAGES/workflow workflow
ln -s $SITE_PACKAGES/scripts scripts
ln -s $SITE_PACKAGES/resources resources

